### ISSUE TITLE
作为调度中心运行时，首次运行安装时，报错请求参数错误

### ISSUE THREAD

**Issue by qiqiaobin** [labulaka521/crocodile#12]
作为调度中心运行时，提示我首次需要运行安装，点击安装，显示报错请求参数错误，然后安装不成功

**Comment by labulaka521** [comment]
有报错的日志吗，贴一下

**Comment by labulaka521** [comment]
你好，解决了吗？

**Comment by qiqiaobin** [comment]
解决了，是你那个开始安装的提示有点误导性，因为你没有默认用户的，其实是注册管理员用户，我一开始没有填用户名和密码，点开始安装报错
