### ISSUE TITLE
你好，看到刚刚支持windows，很好啊，打算使用看看。顺便提几个小建议。

### ISSUE THREAD

**Issue by chaomz** [labulaka521/crocodile#15]
1、为了因应小场景使用，建议redis作为可选使用，存储数据库建议支持sqlite3，这样整个系统会比较轻灵，更加方便易用。
2、建议worker增加在其执行任务过程中向中心提交任务执行进度的报告。
3、建议worker与中心之间以http交互，这样方便可以对接其它语言开发的worker。

最后，感谢作者的无私奉献。

**Comment by labulaka521** [comment]
1.加入redis是为了多调度中心来防止单点挂掉的问题，主要是用来做分布式锁，保存任务状态，及接收实时日志的，如果想用sqlite，v1.1.0前的版本是支持sqlite和mysql的，不过worker节点就需要最新的版本了。
2.这个没办法发送执行任务进度吧，如果你想知道任务的运行状况，可以在你运行的程序输出日志，页面上是可以查看到实时日志的。
3.目前是采用grpc交互的，如果想使用其他语言，可以实现proto文件定义的接口就可以，http这块因为需要worker定时发送心跳信息，注册等问题目前没法支持http。

**Comment by l-we** [comment]
还不如用etcd呢，原生 内嵌 高性能 分布式

**Comment by labulaka521** [comment]
@l-we 当初想过，但是放弃了，因为要存储list，这个主要保存实时日志的，etcd这个没有办法实现的吧

**Comment by l-we** [comment]
> @l-we 当初想过，但是放弃了，因为要存储list，这个主要保存实时日志的，etcd这个没有办法实现的吧

我目前用的是 Dkron，可以参考一下 核心用的是 https://github.com/hashicorp/go-plugin 和 https://github.com/tidwall/buntdb
