### ISSUE TITLE
路径参数在Windows下不可用

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#21]
![TIM截图20200610150903](https://user-images.githubusercontent.com/40453115/84237853-a8f8a680-ab2c-11ea-8336-421528666bcd.jpg)

我使用了 相对路径 ". " ，绝对路径 ，转义字符 \\ ，都不能正确输出日志。

**Comment by yichengsd** [comment]
文件的注释有点问题。不是“日志路径”，是“日志文件名”

**Comment by labulaka521** [comment]
windows上面可能和linux上有些差异，在linux上是正常的 可以看看 https://github.com/natefinch/lumberjack

**Comment by yichengsd** [comment]
> windows上面可能和linux上有些差异，在linux上是正常的 可以看看 https://github.com/natefinch/lumberjack

是的。日志工作正常。
配置文件重关于“日志路径”的注释说明 建议修改一下。
最好参数名 "logpath"一起改一下。

Windows下面路径的 \\ 需要用 \\ \\ 进行转义。

**Comment by labulaka521** [comment]
好的，谢谢反馈
