### ISSUE TITLE
如何安装成为Linux或Windows服务

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#23]
如题

**Comment by labulaka521** [comment]
linux使用systemd 或者supervisor
windows不太熟悉

**Comment by yichengsd** [comment]
systemd创建自定义服务(Ubuntu)
https://www.cnblogs.com/wintersoft/p/9937839.html

windows自定义程序开机启动
https://cloud.tencent.com/developer/article/1389332
