### ISSUE TITLE
系统初始化完成，用户登录报错

### ISSUE THREAD

**Issue by luge007** [labulaka521/crocodile#25]
![image](https://user-images.githubusercontent.com/67366265/85557470-5f46aa80-b65a-11ea-8e19-80a752afbd36.png)
![image](https://user-images.githubusercontent.com/67366265/85557539-6f5e8a00-b65a-11ea-803a-84e7ec1c826b.png)

启动 server和client之后，第一次输入用户名密码 报错

**Comment by yichengsd** [comment]
第一次的时候应该是让你新建账户。
你重新初始化一下数据库试试？

**Comment by 741369** [comment]
我这边用docker装也报这个错。看了一下，是用户表没记录，初始化时 error	model/install.go:124	conn.ExecContext failed	{"error": "Error 1065: Query was empty"} 。添加用户之后，权限不对。
![image](https://user-images.githubusercontent.com/13210977/88924329-b0733b00-d2a5-11ea-958b-42e9569318a4.png)
你们权限是uid，但是casbin_rule里面是admin

**Comment by labulaka521** [comment]
程序启动后会有一个界面是让你输入用户名和密码的
![image](https://user-images.githubusercontent.com/24547356/88927924-be778a80-d2aa-11ea-864c-9432891da736.png)
创建好用户后这个表里就会有uid，然后一个uid会对应admin、normal等等，这就表示这个用户是管理员还是普通用户，如果用户是Admin，表里Admin对应的url就是这个用户可以访问的url，这是rabc模型，如果有兴趣可以看看
不需要你自已去数据库添加数据，只需要在网页就行了

**Comment by labulaka521** [comment]
启动后没创建用户之前是会报这些错的，你只需要打开ip:8080然后初始化用户密码就可以登录了

**Comment by 741369** [comment]
嗯嗯，多谢，我一会再看看，就是install的时候失败了。执行sql语句报错  error model/install.go:124 conn.ExecContext failed {"error": "Error 1065: Query was empty"} 。我一会再看看。我自己插入用户和权限就OK了
