### ISSUE TITLE
日志管理-日志过滤不友好

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#26]
![image](https://user-images.githubusercontent.com/40453115/85935155-0314ac80-b920-11ea-8fba-cc2542f4643f.png)

日志管理的右上角，过滤日志。
如果 任务名称 留空，单选 状态，就报错，不能执行。
如果 任务名称 不输入全称的话，查询不出结果。

建议修改： 任务名称 为空的话，直接按状态 查询结果；任务名不为空的话，模糊查询。

**Comment by labulaka521** [comment]
1.已经修复报错
2.已采用查询日志时任务名为模糊查询，为空则不查询
