### ISSUE TITLE
日志遗漏？

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#27]
![image](https://user-images.githubusercontent.com/40453115/85935192-9817a580-b920-11ea-9539-79966e09b4c0.png)

配置了钉钉通知。
钉钉已经通知了任务执行成功。
日志管理中，查询不到。

**Comment by labulaka521** [comment]
你看下数据库里有这条日志吗 表名叫crocodile_log

**Comment by yichengsd** [comment]
查询了。
数据库中没有这条

而且发现一个问题，我执行的python 命令大约 50秒左右就关闭了，没有日志信息。

**Comment by labulaka521** [comment]
执行时日志会实时的返回到调度中心后保存到redis里，然后执行完成后会从redis读取后保存到mysql，你可以在任务运行的过程中看看有没有redis有没有这个任务的信息，我今天回去试下

**Comment by yichengsd** [comment]
执行时，可以在实时日志中看到信息，但是结束后在日志查询中看不到相关的日志。
![image](https://user-images.githubusercontent.com/40453115/86083494-00a38580-bacd-11ea-94bf-3a90d0cfea38.png)

![image](https://user-images.githubusercontent.com/40453115/86083543-26c92580-bacd-11ea-821b-a9b00044e408.png)

redis可以登录，运行正常。
![image](https://user-images.githubusercontent.com/40453115/86083256-4dd32780-bacc-11ea-9226-78b2773cf762.png)


另外，我的页面经常报 network error 。

**Comment by labulaka521** [comment]
日志太多了，一万多行，估计保存到mysql的时候太大了，默认日志字段时`TEXT`https://github.com/labulaka521/crocodile/blob/dev/sql/log.sql#L9 你把数据库的这个字段改成`MEDIUMTEXT`试试，

**Comment by yichengsd** [comment]
我这个日志是调试使用的。
我把命令行的日志输出关掉了，直接输出文件。
可以正常执行了。

**Comment by labulaka521** [comment]
@yichengsd 嗯嗯 那就确实是日志太大 数据库的字段保存不了了

**Comment by labulaka521** [comment]
@yichengsd 这个问题是代码里有个问题  现在已经修复
