### ISSUE TITLE
执行任务的时候调度进程会down

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#28]
另一台服务器上的任务。python脚本，每三秒抓取一次网页，共执行3000次。
能够启动，启动以后会报 进程down，然后重启，然后无故终止。
这个任务没有在命令行输出日志。

![image](https://user-images.githubusercontent.com/40453115/86117101-09ae4a00-bb01-11ea-895d-a6874422898d.png)

![image](https://user-images.githubusercontent.com/40453115/86117826-4cbced00-bb02-11ea-8f11-d0f34f12f754.png)

![image](https://user-images.githubusercontent.com/40453115/86117759-2dbe5b00-bb02-11ea-84e2-def0f35694e8.png)

**Comment by labulaka521** [comment]
看来是客户端不停的挂 但是我这里没有复现出来

**Comment by yichengsd** [comment]
> 看来是客户端不停的挂 但是我这里没有复现出来

我检查一下日志

**Comment by yichengsd** [comment]
我检查了一下，不是客户端会挂。
是服务端的状态没有响应，拒绝了。不知是哪里设置问题还是服务端不稳定？
![TIM截图20200715164702](https://user-images.githubusercontent.com/40453115/87525050-8a517680-c6bb-11ea-96a0-ff8f6df9f1f7.jpg)

**Comment by labulaka521** [comment]
麻烦看下服务端有关与这个url请求错误的日志吗？连接被重置？

**Comment by labulaka521** [comment]
或者更新一个程序，下载最新的替换下，看看还存在相同的问题吗

**Comment by yichengsd** [comment]
下载了最新的版本，仍然会出现这个错误

![image](https://user-images.githubusercontent.com/40453115/87531543-6e060780-c6c4-11ea-808e-d740208ff2ec.png)

![image](https://user-images.githubusercontent.com/40453115/87531476-5890dd80-c6c4-11ea-9622-f6e158c06ba0.png)

**Comment by yichengsd** [comment]
你测试环境是什么版本？我想重装一下服务。

**Comment by labulaka521** [comment]
@yichengsd 就下载最新的版本就行

**Comment by yichengsd** [comment]
> @yichengsd 就下载最新的版本就行

我的意思是你的测试环境，liunx ，mysql和redis是什么版本。

**Comment by labulaka521** [comment]
mysql 和 redis都是docker-compose里的那个版本，在centos7上面跑的

**Comment by yichengsd** [comment]
我安装了 centos8， redis 5.0.7，mysql8 ，并更换了网段，目前貌似稳定了。

我修改客户机到新版软件的时候，报错如下，具体是什么意思？我修改了客户机端口号到8099，就可以用了。我修改成0 随机 ，也不行。
![image](https://user-images.githubusercontent.com/40453115/87632636-5a15e080-c76c-11ea-8b2a-537a9358ab45.png)

**Comment by labulaka521** [comment]
第一个是地址本来是唯一的但是发生冲突了，你能看下你数据库表crocodile_host里addr字段有这个值吗？
第二个是host表addr字段有点短，长度需要增加一点就可以了，谢谢反馈

**Comment by yichengsd** [comment]
好的，我检查一下，把它删除掉。

主机这里确实有点问题，下面统计的是4台，上面列表里只有3台。
![image](https://user-images.githubusercontent.com/40453115/87634461-deb62e00-c76f-11ea-88f7-2b6f9b189bdc.png)

在主机组的地方，可以选择4台。
![image](https://user-images.githubusercontent.com/40453115/87634561-17ee9e00-c770-11ea-9fc4-2362e6004655.png)

**Comment by yichengsd** [comment]
目前我使用的环境 为 CentOS Linux release 8.2.2004 (Core)
Redis server v=5.0.3 sha=00000000:0 malloc=jemalloc-5.1.0 bits=64
mysql  Ver 8.0.17 for Linux on x86_64 (Source distribution)
/crocodile-linux-amd64 version Version   : v1.1.5 Commit    : 0f33f88 BuildDate : 2020-07-11
已经稳定运行一天了。

之前是Ubuntu 20.04 LTS ，redis 5.0.7 ，可能是个兼容性问题。

**Comment by yichengsd** [comment]
这个问题重新描述一下：
怀疑 当服务端和客户端连接不上的时候，客户端正在执行的任务会中断，建议加强 程序的健壮性设计。
