### ISSUE TITLE
安装初始化时出错了

### ISSUE THREAD

**Issue by daniel-007** [labulaka521/crocodile#29]
![image](https://user-images.githubusercontent.com/21231495/86203468-ad4a3980-bb97-11ea-9769-18bf933cf4cf.png)
导致出错原因如图，原因是我本地数据库环境里，有好几个库里有casbin_rule表。
建议在sql查询语句里增加：table_schema = '库名' 。

**Comment by labulaka521** [comment]
把数据库全部删除，然后再启动后初始化用户信息试试
