### ISSUE TITLE
总是报一个错误

### ISSUE THREAD

**Issue by iLay1678** [labulaka521/crocodile#3]
error	hostgroup/hostgroup.go:278	model.GetHostsByHGID	{"error": "can not find hostid", "errorVerbose": "can not find hostid\ngithub.com/labulaka521/crocodile/core/model.GetHostByIDS\n\t/home/runner/work/crocodile/crocodile/core/model/host.go:228\ngithub.com/labulaka521/crocodile/core/model.GetHostsByHGID\n\t/home/runner/work/crocodile/crocodile/core/model/hostgroup.go:191\ngithub.com/labulaka521/crocodile/core/router/api/v1/hostgroup.GetHostsByIHGID\n\t/home/runner/work/crocodile/crocodile/core/router/api/v1/hostgroup/hostgroup.go:276\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147\ngithub.com/labulaka521/crocodile/core/middleware.Oprtation.func1\n\t/home/runner/work/crocodile/crocodile/core/middleware/operation.go:61\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147\ngithub.com/labulaka521/crocodile/core/middleware.PermissionControl.func1\n\t/home/runner/work/crocodile/crocodile/core/middleware/auth.go:118\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147\ngithub.com/labulaka521/crocodile/core/middleware.ZapLogger.func1\n\t/home/runner/work/crocodile/crocodile/core/middleware/zaplogger.go:17\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147\ngithub.com/gin-gonic/gin.RecoveryWithWriter.func1\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/recovery.go:83\ngithub.com/gin-gonic/gin.(*Context).Next\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/context.go:147\ngithub.com/gin-gonic/gin.(*Engine).handleHTTPRequest\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:403\ngithub.com/gin-gonic/gin.(*Engine).ServeHTTP\n\t/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.5.0/gin.go:364\nnet/http.serverHandler.ServeHTTP\n\t/opt/hostedtoolcache/go/1.13.8/x64/src/net/http/server.go:2802\nnet/http.(*conn).serve\n\t/opt/hostedtoolcache/go/1.13.8/x64/src/net/http/server.go:1890\nruntime.goexit\n\t/opt/hostedtoolcache/go/1.13.8/x64/src/runtime/asm_amd64.s:1357"}

**Comment by iLay1678** [comment]
Get Rpc Conn Failed From Hostgroup 22222[241645505837273088] Err: Can't Get Valid Worker Host

主机组内有一台主机可以正常运行任务，有两台就会报这个错误

**Comment by labulaka521** [comment]
@iLay1678 谢谢反馈，抱歉这里有个bug，我之前没测试到，现在已经修复

**Comment by labulaka521** [comment]
最新编译的可以在这里下载 https://github.com/labulaka521/crocodile/releases/tag/v1.0.1

**Comment by labulaka521** [comment]
你好新的版本已经发布  https://github.com/labulaka521/crocodile/releases/tag/v1.0.1 下载后替换就可以

**Comment by iLay1678** [comment]
ok,新版本正常

**Comment by labulaka521** [comment]
刚发布时间可能有一些bug，希望及时升级哈
