### ISSUE TITLE
server端CPU占用很高

### ISSUE THREAD

**Issue by huangdeyong** [labulaka521/crocodile#31]
![image](https://user-images.githubusercontent.com/16560709/87156770-c5386080-c2ef-11ea-9739-7c0cbf4923c8.png)

![image](https://user-images.githubusercontent.com/16560709/87156802-d2ede600-c2ef-11ea-8b22-fa2a8ad6311f.png)

centos7下使用docker启动了服务，但是cpu占用很高，目前服务持续运行有4周

**Comment by labulaka521** [comment]
@huangdeyong 你好 请执行下wget http://ip:port/debug/pprof/profile?second=15 -O crocodile_profile 然后把下载的文件上传下吗 我分析一下

**Comment by labulaka521** [comment]
@huangdeyong 目前这个高cpu的重启过吗 如果重启了 那请帮忙注意下 如果cpu又高了 请执行下 然后把结果发到这里

**Comment by labulaka521** [comment]
感谢反馈，这个问题已经修复，请下载最新版本替换
