### ISSUE TITLE
同时间点执行多个任务，会大概率性出现任务调度失败

### ISSUE THREAD

**Issue by huangdeyong** [labulaka521/crocodile#32]
使用场景：昨天17点有同步dev分支的代码，主要修复cpu过高的问题。但是出现了新的情况：每2分钟执行三个任务，但是会概率性出现调度失败。失败日志截图如下：
![image](https://user-images.githubusercontent.com/16560709/87376024-13828380-c5be-11ea-8dcd-d9e3da7f5b3a.png)
![image](https://user-images.githubusercontent.com/16560709/87377557-a58a8c00-c5be-11ea-9910-644e11216c1d.png)
![image](https://user-images.githubusercontent.com/16560709/87377414-97d50680-c5be-11ea-9525-ce58d21fbc0f.png)

**Comment by labulaka521** [comment]
这个错误是任务被手动停止执行产生的错误，你没有手动取消运行吗？

**Comment by labulaka521** [comment]
错误任务中 详情那里的日志是什么

**Comment by huangdeyong** [comment]
> 这个错误是任务被手动停止执行或者任务运行超时被取消调用产生的错误，你没有做相关操作吗

没有任何相关操作哦。隔天过来查看日志，就发现有错误日志输出了

**Comment by huangdeyong** [comment]
> 错误任务中详情那里的日志是什么

![image](https://user-images.githubusercontent.com/16560709/87668136-25bb1800-c79e-11ea-9e29-4e804d0054a7.png)
是指这个吗？

**Comment by yichengsd** [comment]
> > 错误任务中详情那里的日志是什么
> 
> ![image](https://user-images.githubusercontent.com/16560709/87668136-25bb1800-c79e-11ea-9e29-4e804d0054a7.png)
> 是指这个吗？

参考一下我这个，你的页面上会不会出现network error #28

**Comment by huangdeyong** [comment]
> > > 错误任务中详情那里的日志是什么
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16560709/87668136-25bb1800-c79e-11ea-9e29-4e804d0054a7.png)是指这个吗？
> 
> 参考一下我这个，你的页面上会不会出现网络误差#28

没有出现网络误差提示哦。

**Comment by labulaka521** [comment]
> > 错误任务中详情那里的日志是什么
> 
> ![image](https://user-images.githubusercontent.com/16560709/87668136-25bb1800-c79e-11ea-9e29-4e804d0054a7.png)
> 是指这个吗？

建议更新版本试试呢，我回去再排查下，目前这个错误只可能取消任务后的返回

**Comment by lorock** [comment]
错误信息 : 取消调用  这类信息大概占10%，90%的任务都是成功的

**Comment by labulaka521** [comment]
> 错误信息 : 取消调用 这类信息大概占10%，90%的任务都是成功的

任务设没设置超时时间，还有麻烦把程序版本信息贴下 `crocodile version`

**Comment by labulaka521** [comment]
@lorock 谢谢反馈 现在已经定位到问题 已经修改 我测试一晚上如果明天没问题就会发新的版本

**Comment by labulaka521** [comment]
已修复 新版已经发布
