### ISSUE TITLE
1.1.5版本 ，收不到钉钉通知，如何排查？

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#34]
报错日志如下
[root@croco crocodile]# ./crocodile-linux-amd64 version
Version   : v1.1.5
Commit    : 0f33f88
BuildDate : 2020-07-11
[root@croco crocodile]# cat crocodile.log | grep dingtalk
2020-07-21T09:01:19.514+0800    error   alarm/alarm.go:271      send dingding notify failed     {"error": "errmsg: invalid timestamp, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq] errcode: 310000"}

**Comment by yichengsd** [comment]
服务器时间是正确的。和ntp同步的。
[root@croco crocodile]# date
Tue Jul 21 09:45:22 CST 2020

**Comment by yichengsd** [comment]
配置文件的格式没有修改吧？我从旧版直接复制过来的。

**Comment by labulaka521** [comment]
@yichengsd 配置文件没有更改，你是用的加签的方式吗？

**Comment by yichengsd** [comment]
是的。加签方式。
![image](https://user-images.githubusercontent.com/40453115/88012547-c74eba80-cb4c-11ea-88db-420dbcf3533d.png)

**Comment by lorock** [comment]
貌似和我的问题一样，重新启动之后可以恢复，过一段时间又不行了，同时后台有大量的“取消调用”消息

**Comment by labulaka521** [comment]
> 是的。加签方式。
> ![image](https://user-images.githubusercontent.com/40453115/88012547-c74eba80-cb4c-11ea-88db-420dbcf3533d.png)

我自已在我本地测试报警没问题呀，也是用的加签的方式，你看看是不是你本地的时间的问题，因为在钉钉的开发文档发送信息需要携带本地的时间戳，如果服务器与钉钉那边时间差距过大可能就会异常

**Comment by labulaka521** [comment]
![IMG_3D573FEA635A-1](https://user-images.githubusercontent.com/24547356/88304359-bd8aaa00-cd3a-11ea-8e35-55ff9b00cd36.jpeg)
这是钉钉上收到的信息，我还特意测试过这个接口的代码也没问题，或者你可以先选用 自定义关键字或者IP地址的方式

**Comment by labulaka521** [comment]
最新版已经修复这个问题
