### ISSUE TITLE
v1.1.16运行约两天的样子，server无法正常提供服务

### ISSUE THREAD

**Issue by lorock** [labulaka521/crocodile#35]
报错如下，重新启动server端后恢复正常
{"level":"info","time":"2020-07-28T01:12:18.964+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.551277}
{"level":"info","time":"2020-07-28T01:12:19.263+0800","line":"schedule/schedule2.go:571","msg":"start run task","taskname":"check_website_api.dstcar.com"}
{"level":"debug","time":"2020-07-28T01:12:19.263+0800","line":"schedule/schedule2.go:513","msg":"start get lock","taskid":"290165913800413184"}
{"level":"error","time":"2020-07-28T01:12:19.264+0800","line":"schedule/schedule2.go:643","msg":"model.GetTaskByID failed","taskid":"290165913800413184","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"debug","time":"2020-07-28T01:12:19.265+0800","line":"schedule/schedule2.go:528","msg":"start release lock","taskid":"290165913800413184"}
{"level":"debug","time":"2020-07-28T01:12:19.265+0800","line":"schedule/schedule2.go:599","msg":"stop expire lock","lockid":"task:runlock:290165913800413184"}
{"level":"debug","time":"2020-07-28T01:12:21.973+0800","line":"schedule/grpc_impl.go:207","msg":"recv hearbeat","addr":"127.0.0.1:19588"}
{"level":"error","time":"2020-07-28T01:12:21.974+0800","line":"middleware/grpcmidd.go:28","msg":"resp failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"info","time":"2020-07-28T01:12:21.974+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.039417}
{"level":"error","time":"2020-07-28T01:12:22.088+0800","line":"middleware/auth.go:108","msg":"checkAuth failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"warn","time":"2020-07-28T01:12:22.088+0800","line":"middleware/zaplogger.go:41","msg":"Gin","uid":"289850216985661440","method":"get","statuscode":10401,"reqip":"192.168.200.28","latency(ms)":1.281325,"url":"/api/v1/notify","respsize":36}
{"level":"debug","time":"2020-07-28T01:12:24.978+0800","line":"schedule/grpc_impl.go:207","msg":"recv hearbeat","addr":"127.0.0.1:19588"}
{"level":"error","time":"2020-07-28T01:12:24.980+0800","line":"middleware/grpcmidd.go:28","msg":"resp failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"info","time":"2020-07-28T01:12:24.980+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.379629}
{"level":"error","time":"2020-07-28T01:12:27.087+0800","line":"middleware/auth.go:108","msg":"checkAuth failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"warn","time":"2020-07-28T01:12:27.087+0800","line":"middleware/zaplogger.go:41","msg":"Gin","uid":"289850216985661440","method":"get","statuscode":10401,"reqip":"192.168.200.28","latency(ms)":1.247689,"url":"/api/v1/notify","respsize":36}
{"level":"debug","time":"2020-07-28T01:12:27.982+0800","line":"schedule/grpc_impl.go:207","msg":"recv hearbeat","addr":"127.0.0.1:19588"}
{"level":"error","time":"2020-07-28T01:12:27.983+0800","line":"middleware/grpcmidd.go:28","msg":"resp failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"info","time":"2020-07-28T01:12:27.983+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.304077}
{"level":"debug","time":"2020-07-28T01:12:30.985+0800","line":"schedule/grpc_impl.go:207","msg":"recv hearbeat","addr":"127.0.0.1:19588"}
{"level":"error","time":"2020-07-28T01:12:30.986+0800","line":"middleware/grpcmidd.go:28","msg":"resp failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"info","time":"2020-07-28T01:12:30.986+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.220173}
{"level":"warn","time":"2020-07-28T01:12:31.297+0800","line":"schedule/schedule2.go:1081","msg":"task is stop run by auto schedule","taskname":"run_shell","taskid":"290088289640124416"}
{"level":"error","time":"2020-07-28T01:12:32.087+0800","line":"middleware/auth.go:108","msg":"checkAuth failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"warn","time":"2020-07-28T01:12:32.087+0800","line":"middleware/zaplogger.go:41","msg":"Gin","uid":"289850216985661440","method":"get","statuscode":10401,"reqip":"192.168.200.28","latency(ms)":1.41084,"url":"/api/v1/notify","respsize":36}
{"level":"debug","time":"2020-07-28T01:12:33.988+0800","line":"schedule/grpc_impl.go:207","msg":"recv hearbeat","addr":"127.0.0.1:19588"}
{"level":"error","time":"2020-07-28T01:12:33.989+0800","line":"middleware/grpcmidd.go:28","msg":"resp failed","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}
{"level":"info","time":"2020-07-28T01:12:33.989+0800","line":"middleware/grpcmidd.go:36","msg":"[rpc req]","method":"/crocodile.task.Heartbeat/SendHb","req":"port:19588 ","resp":"","reqaddr":"127.0.0.1:39455","latency(ms)":1.355797}
{"level":"info","time":"2020-07-28T01:12:34.263+0800","line":"schedule/schedule2.go:571","msg":"start run task","taskname":"check_website_api.dstcar.com"}
{"level":"debug","time":"2020-07-28T01:12:34.263+0800","line":"schedule/schedule2.go:513","msg":"start get lock","taskid":"290165913800413184"}
{"level":"error","time":"2020-07-28T01:12:34.266+0800","line":"schedule/schedule2.go:643","msg":"model.GetTaskByID failed","taskid":"290165913800413184","error":"conn.PrepareContext failed: Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)"}

**Comment by mywaystay** [comment]
[修改] 修复Can't create more than max_prepared_stmt_count statements
[https://github.com/labulaka521/crocodile/pull/36](url)

**Comment by mywaystay** [comment]
@labulaka521 很多stmt使用完没有关闭哟, 会导致数据库挂掉的

**Comment by mywaystay** [comment]
这些文件里面都有没关闭的stmt
![image](https://user-images.githubusercontent.com/5088165/88637180-672bbb80-d0ec-11ea-8728-67b00b5dd7ee.png)

**Comment by labulaka521** [comment]
@mywaystay 已经全部添加
@lorock 问题已经修复，下载1.1.6替换即可，感谢反馈
