### ISSUE TITLE
v1.1.16使用钉钉推送约1个小时就会报错，重新后恢复，周而复始

### ISSUE THREAD

**Issue by lorock** [labulaka521/crocodile#37]
版本信息：v1.1.6   22850e
报错信息：
{"level":"error","time":"2020-07-29T14:00:30.217+0800","line":"alarm/alarm.go:271","msg":"send dingding notify failed","error":"errmsg: invalid timestamp, more: [https://ding-doc.dingtalk.com/doc#/serverapi2/qf2nxq] errcode: 310000"}

**Comment by lorock** [comment]
重启server服务后可以恢复

**Comment by labulaka521** [comment]
上次也有人报这个错，但是我回去复现没有出现
看看你们服务器的时间是不是有问题，或者你可以使用自定义关键字的方式来报警
我回去再试试

**Comment by lorock** [comment]
服务器时间没有问题，我的服务器10分钟同步一次的，我手动同步时间之后也不能恢复，只有重启才能恢复

**Comment by labulaka521** [comment]
@lorock 你先不要使用加签的方式，使用自定义关键字或者IP，这两种方式不用校验时间戳。我这几天再测试下，看看能不能浮现

**Comment by labulaka521** [comment]
最新版已经修复这个问题

**Comment by HXM1130** [comment]
你们这个问题解决了嘛

**Comment by HXM1130** [comment]
> 最新版已经修复这个问题

最新版本是什么版本啊。？
