### ISSUE TITLE
我想执行一些复杂的 go 程序有办法实现吗？

### ISSUE THREAD

**Issue by x1nchen** [labulaka521/crocodile#38]
我们有很多定时任务，基本都是操作数据库的，所以 main.go 里会 import 包含一些私有仓库的 module，比如

```go
package main

import "xxx.com/go-common/db"

func main() {
      db.CallFunction()
}
```

**Comment by x1nchen** [comment]
我看了 rungolang 的实现，是写入到临时文件然后 go run xxx.go 执行，这个思路挺好的。但是似乎不太适合我的这个场景，因为 run 之前还需要执行 go get ，这个时间损耗太高。

**Comment by labulaka521** [comment]
首次运行的话是需要go get的，后续缓存到go mod cache里应该就不需要了，私有仓库的话只要worker节点可以访问就行了。

**Comment by x1nchen** [comment]
OK。感谢。

**Comment by labulaka521** [comment]
@x1nchen  好的 如果有什么疑问欢迎及时提出
