### ISSUE TITLE
登录时，用户名不支持中文？

### ISSUE THREAD

**Issue by yichengsd** [labulaka521/crocodile#39]

**Comment by yichengsd** [comment]
![image](https://user-images.githubusercontent.com/40453115/88990054-92dabb80-d30f-11ea-9ba9-466aa96e2467.png)

**Comment by labulaka521** [comment]
@yichengsd 目前不支持 改成英文吧

**Comment by yichengsd** [comment]
ok
建议创建的时候给个提示。

**Comment by labulaka521** [comment]
@yichengsd 可以 谢谢反馈

**Comment by labulaka521** [comment]
已添加提示，谢谢反馈，使用v1.1.7版本
