### ISSUE TITLE
docker-compose安装失败

### ISSUE THREAD

**Issue by 741369** [labulaka521/crocodile#40]
![image](https://user-images.githubusercontent.com/13210977/88993976-ed791500-d319-11ea-8a70-027581d4706b.png)
这个问题有空帮忙看一下，

本地安装的问题，建议这里查询加上库名，不然如果其他数据库有casbin_rule就会报错
![image](https://user-images.githubusercontent.com/13210977/88994023-041f6c00-d31a-11ea-87f7-489e2c7c7baf.png)

**Comment by labulaka521** [comment]
你这个是本地数据库有casbin_rule这个表吗

**Comment by labulaka521** [comment]
pr一下吧，谢谢反馈

**Comment by labulaka521** [comment]
#29

**Comment by labulaka521** [comment]
可以采用 #29 的建议

**Comment by labulaka521** [comment]
感谢反馈 已经修复
