### ISSUE TITLE
用户sql也提供下默认用管理员用户呢？

### ISSUE THREAD

**Issue by php2go** [labulaka521/crocodile#41]
用户sql也提供下默认用管理员用户呢？

**Comment by labulaka521** [comment]
不能再页面上创建用户吗？

**Comment by php2go** [comment]
现在一个用户没有，那我也得登录进去在创建用户吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "labulaka521/crocodile"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月31日(星期五) 下午4:05
收件人:&nbsp;"labulaka521/crocodile"<crocodile@noreply.github.com&gt;;
抄送:&nbsp;"Mreden"<913057891@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [labulaka521/crocodile] 用户sql也提供下默认用管理员用户呢？ (#41)





 
不能再页面上创建用户吗？

**Comment by labulaka521** [comment]
启动程序后打开页面有一个初始化用户的页面创建即可，可以使用刚发布的版本v1.1.7修复了几个bug
