### ISSUE TITLE
主机怎么添加？

### ISSUE THREAD

**Issue by zhouyg** [labulaka521/crocodile#42]
![image](https://user-images.githubusercontent.com/6834964/89119356-8c4f6e00-d4e0-11ea-9d5d-31a722209994.png)
![image](https://user-images.githubusercontent.com/6834964/89119366-a8eba600-d4e0-11ea-9da3-f413a314bd0f.png)
![image](https://user-images.githubusercontent.com/6834964/89119375-b2750e00-d4e0-11ea-9ad3-791bad442672.png)
你好，我按github 上的操作，主机列表还是空的，要怎样才能添加主机

![image](https://user-images.githubusercontent.com/6834964/89119392-d3d5fa00-d4e0-11ea-9322-bbf121624ce9.png)
![image](https://user-images.githubusercontent.com/6834964/89119408-f36d2280-d4e0-11ea-99a3-ab30d22fa7ee.png)

1、支持四种调度算法随机、轮训、Worker权重、Worker最少任务数来调用Worker运行任务
假如我新增一个任务（不希望多个进程同时执行，如果同时跑需要加锁，所以脚本想做到同一时间只有一个worker在跑），定时跑，同一时间是不是只会有一个worker处理
2、看页面可以直接写脚本，但是不好进行代码维护，所以是可以直接通过页面的脚本去调用具体路径下的脚本吧
例如，shell 中 调用具体路径下的python 脚本。
这种方式要怎么写才能捕获到python 脚本的异常返回，上报异常。有没有demo 参考
![image](https://user-images.githubusercontent.com/6834964/89119427-1697d200-d4e1-11ea-872e-434dde75ad65.png)
shell 脚本异常  应该是通过exit xx   来返回错误码 吧？

**Comment by labulaka521** [comment]
客户端注册成功了 页面看不到吗？你看下服务端有收到注册的请求吗？或者看下有什么报错吗

**Comment by labulaka521** [comment]
1
一个任务只会被分发到一个worker中运行
2
现在是把程序运行打印出的信息全部返回，捕获一场可以自已代码里做

**Comment by zhouyg** [comment]
> 1
> 一个任务只会被分发到一个worker中运行
> 2
> 现在是把程序运行打印出的信息全部返回，捕获一场可以自已代码里做

![image](https://user-images.githubusercontent.com/6834964/89120111-37165b00-d4e6-11ea-9a82-e58b1aba31a9.png)
创建任务选择shell 的方式，怎么写才会表示异常， 
#!/usr/bin/env sh
function main() {
    echo "run shell"   // 这只是打印日志吧？  如果执行失败，需要怎么写:  exit code (code 为非0 整数) 吗
}

main

**Comment by labulaka521** [comment]
现在判断异常就是默认就是判断程序运行的返回码是不是0，当然还提供了判断程序输出是否包含某个字段的方式来判断是否正常运行

**Comment by labulaka521** [comment]
exit 1 这就是执行异常

**Comment by zhouyg** [comment]
> exit 1 这就是执行异常

是不是应该直接支持执行shell 命令，例如直接填写： python   mycode.py  , 这种形式应该是比较参见的，没必要多包裹一层（通过脚本调用另外一个脚本）

**Comment by zhouyg** [comment]
> > exit 1 这就是执行异常
> 
> 是不是应该直接支持执行shell 命令，例如直接填写： python mycode.py , 这种形式应该是比较参见的，没必要多包裹一层（通过脚本调用另外一个脚本）

直接在页面上写代码，写的代码不会维护（代码一般会考虑上次git）,  所以建议加上支持 go 调用 填写 的命令，这样我只需要维护一份代码

**Comment by zhouyg** [comment]
![image](https://user-images.githubusercontent.com/6834964/89120743-4cda4f00-d4eb-11ea-88bf-e13e3b494051.png)
![image](https://user-images.githubusercontent.com/6834964/89120750-55328a00-d4eb-11ea-9961-b1f6f9369d5f.png)
![image](https://user-images.githubusercontent.com/6834964/89120755-5c599800-d4eb-11ea-97e6-7a06961d45aa.png)

这个不应该报错吗？

**Comment by labulaka521** [comment]
@zhouyg shell脚本返回码是0，怎么会报错？
