### ISSUE TITLE
任务调度停止

### ISSUE THREAD

**Issue by CLannadZSY** [labulaka521/crocodile#45]
我停止了任务的调度, 但是我的 server 日志中一直在显示 `task is stop run by auto schedule`, 只有当我删除了任务才会停止显示
![image](https://user-images.githubusercontent.com/38000492/92130094-ec666680-ee36-11ea-82ff-ecb77fc09045.png)

![image](https://user-images.githubusercontent.com/38000492/92130055-dfe20e00-ee36-11ea-8325-1f1f4fbb9c3e.png)

**Comment by labulaka521** [comment]
任务停止后，但是还会检测下一次的运行时间只是运行的时候会检测是否被停止，如果停止了就不会运行了，现在只是把这个日志打印出来了，应该去掉，谢谢反馈
