### ISSUE TITLE
如何在 k8s 中优雅的部署crocodile呢？

### ISSUE THREAD

**Issue by bingoku** [labulaka521/crocodile#49]
现象就是获取的 worker IP 并不是容器的，而是主机的 IP。
![image](https://user-images.githubusercontent.com/4134788/95728797-84fdcb00-0cae-11eb-8eeb-6b27881ea72b.png)

另外还希望，提供一个接口，可以删除原来的老的 worker 主机。
因为需要，在在这个 pod 停止的，清理一下 worker 主机。
看起来像

![image](https://user-images.githubusercontent.com/4134788/95729538-9f847400-0caf-11eb-8ad2-16604e8491a3.png)

**Comment by labulaka521** [comment]
能详细说下你们容器之间通信的流程吗，我不太清楚k8s 容器之间通信的流程，这个workerip 是worker向调度中心通信时，调度中心收到的请求的地址，如果和worker容器的ip不一样看来是做了一个类似nat转换的过程，把ip映射到了另外一个ip，如果是这样那在你们容器通信的时候能获取到连接发起方的容器IP吗

**Comment by bingoku** [comment]
ipvs 来做的网络，感觉不应该识别出来是主机 IP，而是容器自身的 IP。

**Comment by labulaka521** [comment]
你可以先做下测试，起一个web服务，然后请求看看

**Comment by liqiangno1** [comment]
我觉得这里主要问题是，因为K8S里面的容器每次重启就会导致IP变化，所以每次worker重启都要重新更改主机组，把变更后的worker加进去，这样就会很麻烦

**Comment by labulaka521** [comment]
@liqiangno1 确实，现在的通信只是client到server来让server发现，没有在server主动注册，可能需要加上这个才可以
