### ISSUE TITLE
日志管理功能问题

### ISSUE THREAD

**Issue by sofire** [labulaka521/crocodile#7]
清理日志功能：
任务名称、时间等 都是必填，否则会报错；界面显示的不是必填

如果没有任务名称，报错 “请求参数错误”;  这个操作没成功，出错了，审计日志 也会记录

没有时间，报错 error，错误不清晰

  error   middleware/operation.go:146     json.Unmarshal failed   {"error": "json: cannot unmarshal string into Go struct field Cleanlog.preday of type int64"}

没有搜索按钮

如果没有输入任务名称，则不显示日志列表。如果显示 所有的日志，可能会更方便些。

**Comment by labulaka521** [comment]
感谢反馈
日志管理刚开始主要是想着只限于查看某个任务日志，现在一想确实不太好，默认返回最新的日志更好点

>没有时间，报错 error，错误不清晰
这个问题是由于本来时间应该传int 如果未填就传了一个空字符串，所以在审计的时间转换失败了，这是个bug

前端可能还要做一些限制

搜索的话 只在部分页面做了搜索选项 我看看还可以对哪些数据做搜索，或者你说下你希望有哪些

**Comment by sofire** [comment]
先有基本功能吧
